### ISSUE TITLE
Add option to kondense only cpu or kondense only memory

### ISSUE THREAD

**Issue by MathieuCesbron** [unagex/kondense#12]
Right now, kondense is updating memory and cpu for each container in a pod.

An environment variable in the `kondense` container could make it so that we only update memory or cpu.

example:
```yaml
      - name: kondense
        image: kondense/kondense:1.0.1
        resources:
          limits:
            cpu: 80m
            memory: 100M
        env:
        - name: STRESS-NG_MODE
          value: "cpu"
          # value: "cpu" || "memory" || "all"
```
